### ISSUE TITLE
Problems with incomplete collections

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#276]
Hi @miguelriemoliveira ,

How does ATOM work with incomplete collections? 

When running:

`rosrun atom_calibration calibrate -json /home/daniela/datasets/dataset_31_03_2021/data_collected.json 'lambda name: int(name) < 50' -nig 0.05 0.025 -ss 1`

I just got the error:

`Removing collection 1 -> pattern was not found in sensor hand_camera (incomplete collection).
Traceback (most recent call last):
  File "/home/daniela/catkin_ws/devel/lib/atom_calibration/calibrate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 543, in <module>
    main()
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 112, in main
    dataset = filterCollectionsFromDataset(dataset, args)  # filter collections
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_core/src/atom_core/dataset_io.py", line 361, in filterCollectionsFromDataset
    for collection_key, collection in dataset['collections'].items():
RuntimeError: dictionary changed size during iteration`

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

I think it was a problem of having to adjust this particular code to python3. I've done it.

Cannot test because you did not give me the **dataset_31_03_2021**. Can you test and close if its fixed?

**Comment by danifpdra** [comment]
It works when removing the incomplete collections. If I use the -uic flag I get the following error:

`Removing collection 8: at least one detection by a camera should be present.
Traceback (most recent call last):
  File "/home/daniela/catkin_ws/devel/lib/atom_calibration/calibrate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 543, in <module>
    main()
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 112, in main
    dataset = filterCollectionsFromDataset(dataset, args)  # filter collections
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_core/src/atom_core/dataset_io.py", line 397, in filterCollectionsFromDataset
    for collection_key, collection in dataset['collections'].items():
RuntimeError: dictionary changed size during iteration`

**Comment by miguelriemoliveira** [comment]
I will try tonight. Give me the dataset please.

**Comment by danifpdra** [comment]
Here it is: [dataset_31_03_2021.zip](https://github.com/lardemua/atom/files/6246239/dataset_31_03_2021.zip)

**Comment by miguelriemoliveira** [comment]
I think now its solved. Tested and it works. Let me know if you need anything else.

Also I would like to discuss with you the organization of the results in a new repository or some shared folder. Can we talk 15 ou 20 mins? Tell me when you have time in the next days (or next week).

**Comment by danifpdra** [comment]
I don't have anything scheduled for the next few days. Give me a call whenever you want to meet.
