### ISSUE TITLE
Does not work if some of the collections in the middles, e.g. '1' are removed. An easy test is to run a -csf "lambda x: x in ['0', '2']"

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#402]
```
    # TODO does not work if some of the collections in the middles, e.g. '1' are removed. An easy test is to run a -csf "lambda x: x in ['0', '2']"
```

https://github.com/lardemua/atom/blob/c061428a5af2bcd59b3cf0139b9594f2d55fb388/atom_calibration/scripts/dataset_playback#L53

**Comment by miguelriemoliveira** [comment]
To reproduce:

    clear && rosrun atom_calibration dataset_playback -json $ATOM_DATASETS/larcc/dataset_train/dataset.json -csf "lambda x: x in ['0', '2'] " -uic -si  -ow 

crashes with:

```bash
Traceback (most recent call last):
  File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/scripts/dataset_playback", line 247, in <module>
    main()
  File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/scripts/dataset_playback", line 238, in main
    visualizationFunction(models=models, selection=selection, clicked_points=clicked_points)
  File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/dataset_playback/visualization.py", line 582, in visualizationFunction
    collection = dataset['collections'][selected_collection_key]
KeyError: '1'
```
