### ISSUE TITLE
Bug found in set initial estimate initiation

### ISSUE THREAD

**Issue by manuelgitgomes** [lardemua/atom#481]
When retrieving images for my dissertation, I found a bug while running:

```bash
roslaunch atlascar2_calibration set_initial_estimate.launch
```

The error is as follows:

```bash
Traceback (most recent call last):9   Duration: 0.100829 / 351.032000               
  File "/home/nel/catkin_ws/devel/lib/atom_calibration/set_initial_estimate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/nel/catkin_ws/src/calibration/atom/atom_calibration/scripts/set_initial_estimate", line 195, in <module>
    first_guess.init()
  File "/home/nel/catkin_ws/src/calibration/atom/atom_calibration/scripts/set_initial_estimate", line 72, in init
    self.sensors.append(Sensor(name, self.server, self.menu, **params))
  File "/home/nel/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/initial_estimate/sensor.py", line 60, in __init__
    self.updateAll()  # update all the transformations
  File "/home/nel/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/initial_estimate/sensor.py", line 159, in updateAll
    self.updatePreT()
  File "/home/nel/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/initial_estimate/sensor.py", line 167, in updatePreT
    self.preT = self.updateT(self.world_link, self.opt_parent_link, rospy.Time.now())
  File "/home/nel/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/initial_estimate/sensor.py", line 176, in updateT
    self.listener.waitForTransform(parent_link, child_link, rospy.Time(), rospy.Duration(1.0))
  File "/opt/ros/noetic/lib/python3/dist-packages/tf/listener.py", line 76, in waitForTransform
    raise tf2_ros.TransformException(error_msg or "no such transformation: \"{}\" -> \"{}\"".format(source_frame, target_frame))
tf2.TransformException: canTransform: target_frame odom does not exist.
```

The problem was solved when placing a `time.sleep` before the initiation of the sensors. So the script changed from this:
https://github.com/lardemua/atom/blob/71e1f78fce2f723e8a991b35f8591167adfd84e4/atom_calibration/scripts/set_initial_estimate#L57-L73

To this:

```python3
        self.createInteractiveMarker(self.config['world_link'])
        self.menu.insert("Save sensors configuration", callback=self.onSaveInitialEstimate)
        self.menu.insert("Reset all sensors to initial configuration", callback=self.onResetAll)
        self.menu.reApply(self.server)

        # Waiting for the loading of the bagfile
        time.sleep(2)

        # For each node generate an interactive marker.
        for name, sensor in self.config['sensors'].items():
            print(Fore.BLUE + '\nSensor name is ' + name + Style.RESET_ALL)
            params = {
                "frame_world": self.config['world_link'],
                "frame_opt_parent": sensor['parent_link'],
                "frame_opt_child": sensor['child_link'],
                "frame_sensor": sensor['link'],
                "marker_scale": self.args['marker_scale']}
            # Append to the list of sensors
            self.sensors.append(Sensor(name, self.server, self.menu, **params))
            print('... done')

```

This might be due to having the bag file in an HDD, making its access slower than the python script. 
How shall we solve this? Should we compromise a few seconds on the initiation for a guaranteed performance?

**Comment by miguelriemoliveira** [comment]
> How shall we solve this? Should we compromise a few seconds on the initiation for a guaranteed performance?

Yes, I think it makes sense to do so.

Thanks @manuelgitgomes

**Comment by manuelgitgomes** [comment]
Ok, then I'll commit my changes!
