### ISSUE TITLE
Bug when trying to collect data

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#494]
I configured the calibration package with a bag called `bag_robot.bag`... I can run the playbag.launch and so on. When I try to calibrate all starts normally with 

```
[ INFO] [1655996287.847086221]: Opening /home/daniela/bagfiles/larcc_real/bag_robot.bag

Waiting 2 seconds after advertising topics...
Argument list={'marker_size': 0.5, 'output_folder': '~/datasets/larcc/larcc_real/train_robot', 'calibration_file': '/home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/calibration/config.yml', 'overwrite': True, 'skip_sensor_labeling': <function <lambda> at 0x7f4a60c7c8b0>}

 done.

Hit space to toggle paused, or 's' to step.
 [RUNNING]  Bag Time: 1655809088.220022   Duration: 0.078337 / 363.480901               

Warning: Dataset /home/daniela/datasets/larcc/larcc_real/train_robot exists.
Moving it to a new folder: /tmp/train_robot_2022-06-23-15-58-08
This will be deleted after a system reboot!
```

Where we can see that the correct bag is being loaded and then I get this error:

```
[]RUNNING]  Bag Time: 1655809089.051331   Duration: 0.909646 / 363.480901               
Traceback (most recent call last):85592   Duration: 0.943907 / 363.480901               
  File "/home/daniela/catkin_ws/devel/lib/atom_calibration/collect_data", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/scripts/collect_data", line 145, in <module>
    data_collector = DataCollectorAndLabeler(args, server, menu_handler)
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py", line 76, in __init__
    self.config = loadConfig(args['calibration_file'])
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_core/src/atom_core/config_io.py", line 144, in loadConfig
    fullpath, name, uri = uriReader(config['bag_file'])
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_core/src/atom_core/config_io.py", line 93, in uriReader
    assert (os.path.exists(fullpath)), Fore.RED + fullpath + ' does not exist.'
AssertionError: /home/daniela/bagfiles/larcc_real/bag_tripod_1min.bag does not exist.
```

Where it says that a bag with a different name does not exist.

Do you know what this is about @miguelriemoliveira ?

**Comment by danifpdra** [comment]
The configuration of the calibration package runs as expected:

```
config_hand_eye.yml
Loading config file /home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/calibration/config_hand_eye.yml
[]
Loading bagfile /home/daniela/bagfiles/larcc_real/bag_robot.bag
Deleting temporary file /tmp/description.urdf
Parsing description file /home/daniela/catkin_ws/src/calibration/larcc/larcc_description/urdf/larcc_improvised.urdf.xacro
Executing command: xacro /home/daniela/catkin_ws/src/calibration/larcc/larcc_description/urdf/larcc_improvised.urdf.xacro -o /tmp/description.urdf
Creating transformation tree using the urdf robot description ...
world
table
tabletop_table
leg1_table
leg2_table
leg3_table
leg4_table
gantry
gantry_gantry
leg1_gantry
leg2_gantry
leg3_gantry
leg4_gantry
bigbeam1_gantry
bigbeam2_gantry
smallbeam1_bigbeam1_gantry
smallbeam2_bigbeam1_gantry
rectangularbeam1_gantry
rectangularbeam2_gantry
rectangularbeam3_gantry
base_link
base_link_inertia
shoulder_link
upper_arm_link
forearm_link
wrist_1_link
wrist_2_link
wrist_3_link
base
flange
tool0
lidar_1_base_link
lidar_1
lidar_2_base_link
lidar_2
lidar_3_base_link
lidar_3
hand_camera_link
hand_camera_rgb_frame
hand_camera_rgb_optical_frame
hand_camera_depth_frame
hand_camera_depth_optical_frame
camera_1_link
camera_1_depth_frame
camera_1_depth_optical_frame
camera_1_rgb_frame
camera_1_rgb_optical_frame
camera_2_link
camera_2_rgb_frame
camera_2_rgb_optical_frame
camera_2_depth_frame
camera_2_depth_optical_frame
camera_3_link
camera_3_rgb_frame
camera_3_rgb_optical_frame
camera_3_depth_frame
camera_3_depth_optical_frame
camera_4_link
camera_4_rgb_frame
camera_4_rgb_optical_frame
camera_4_depth_frame
camera_4_depth_optical_frame
Running verifications ... please wait ...
Sensor depth_camera_1 has throttle
Sensor hand_camera_rgb has throttle
Sensor hand_camera_depth has throttle
Sensor lidar_2 does not have throttle
Sensor camera_4 does not have throttle
Checking if all tf frames exist ...
{'world_link': 'world', 'calibration_pattern.pattern_link': 'world', 'depth_camera_1.child_link': 'camera_1_link', 'depth_camera_1.parent_link': 'bigbeam1_gantry', 'depth_camera_1.link': 'camera_1_depth_optical_frame', 'hand_camera_rgb.child_link': 'hand_camera_rgb_optical_frame', 'hand_camera_rgb.parent_link': 'hand_camera_rgb_frame', 'hand_camera_rgb.link': 'hand_camera_rgb_optical_frame', 'hand_camera_depth.child_link': 'hand_camera_depth_optical_frame', 'hand_camera_depth.parent_link': 'hand_camera_depth_frame', 'hand_camera_depth.link': 'hand_camera_depth_optical_frame', 'lidar_2.child_link': 'lidar_2_base_link', 'lidar_2.parent_link': 'rectangularbeam2_gantry', 'lidar_2.link': 'lidar_2', 'camera_4.child_link': 'camera_4_link', 'camera_4.parent_link': 'bigbeam1_gantry', 'camera_4.link': 'camera_4_rgb_optical_frame'}
TF tree is connected.
Transformations for sensors. Color coding is root link, to be calibrated, dynamic transformation, sensor data frame.
Path from world to sensor depth_camera_1:
[world, gantry, leg1_gantry, bigbeam1_gantry, camera_1_link, camera_1_depth_frame, camera_1_depth_optical_frame]
Path from world to sensor hand_camera_rgb:
[world, table, tabletop_table, base_link, base_link_inertia, shoulder_link, upper_arm_link, forearm_link, wrist_1_link, wrist_2_link, wrist_3_link, flange, hand_camera_link, hand_camera_rgb_frame, hand_camera_rgb_optical_frame]
Path from world to sensor hand_camera_depth:
[world, table, tabletop_table, base_link, base_link_inertia, shoulder_link, upper_arm_link, forearm_link, wrist_1_link, wrist_2_link, wrist_3_link, flange, hand_camera_link, hand_camera_depth_frame, hand_camera_depth_optical_frame]
Path from world to sensor lidar_2:
[world, gantry, leg1_gantry, bigbeam1_gantry, rectangularbeam2_gantry, lidar_2_base_link, lidar_2]
Path from world to sensor camera_4:
[world, gantry, leg1_gantry, bigbeam1_gantry, camera_4_link, camera_4_rgb_frame, camera_4_rgb_optical_frame]
Setting up /home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/launch/playbag.launch ...
Setting up /home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/launch/set_initial_estimate.launch ...
Setting up /home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/launch/collect_data.launch ...
Setting up /home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/launch/calibrate.launch ...
Setting up /home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/launch/dataset_playback.launch ...
Setting up set_initial_estimate.rviz ...
	Generating rviz displays for sensor camera_4 with topic /camera_4/rgb/image_raw (rgb)
	Generating rviz displays for sensor depth_camera_1 with topic /camera_1/depth/image_raw (depth)
	Generating rviz displays for sensor hand_camera_depth with topic /hand_camera/depth/image_rect_raw (depth)
	Generating rviz displays for sensor hand_camera_rgb with topic /hand_camera/color/image_raw (rgb)
	Generating rviz displays for sensor lidar_2 with topic /lidar_2/velodyne_points (lidar3d)
Setting up collect_data.rviz ...
	Generating rviz displays for sensor camera_4 with topic /camera_4/rgb/image_raw (rgb)
	Generating rviz displays for sensor depth_camera_1 with topic /camera_1/depth/image_raw (depth)
	Generating rviz displays for sensor hand_camera_depth with topic /hand_camera/depth/image_rect_raw (depth)
	Generating rviz displays for sensor hand_camera_rgb with topic /hand_camera/color/image_raw (rgb)
	Generating rviz displays for sensor lidar_2 with topic /lidar_2/velodyne_points (lidar3d)
Setting up dataset_playback.rviz ...
	Generating rviz displays for sensor camera_4 with topic /camera_4/rgb/image_raw (rgb)
	Generating rviz displays for sensor depth_camera_1 with topic /camera_1/depth/image_raw (depth)
	Generating rviz displays for sensor hand_camera_depth with topic /hand_camera/depth/image_rect_raw (depth)
	Generating rviz displays for sensor hand_camera_rgb with topic /hand_camera/color/image_raw (rgb)
	Generating rviz displays for sensor lidar_2 with topic /lidar_2/velodyne_points (lidar3d)
Setting up calibrate.rviz ...
	Generating rviz displays for sensor camera_4 with topic /camera_4/rgb/image_raw (rgb)
	Generating rviz displays for sensor depth_camera_1 with topic /camera_1/depth/image_raw (depth)
	Generating rviz displays for sensor hand_camera_depth with topic /hand_camera/depth/image_rect_raw (depth)
	Generating rviz displays for sensor hand_camera_rgb with topic /hand_camera/color/image_raw (rgb)
	Generating rviz displays for sensor lidar_2 with topic /lidar_2/velodyne_points (lidar3d)

Created a calibration configuration summary. Use it to see if the calibration is well set up. Located at:
/home/daniela/catkin_ws/src/calibration/larcc/larcc_calibration/calibration/summary.pdf

Successfully configured calibration package larcc_calibration. You can use the launch files:
roslaunch larcc_calibration playbag.launch
roslaunch larcc_calibration set_initial_estimate.launch
roslaunch larcc_calibration collect_data.launch
roslaunch larcc_calibration dataset_playback.launch
roslaunch larcc_calibration calibrate.launch
```

**Comment by danifpdra** [comment]
I discovered what the problem was. I will fix this now.

**Comment by miguelriemoliveira** [comment]
> I discovered what the problem was. I will fix this now.

Hi @danifpdra ,

sorry, only now I am reading this. Can you describe what the problem was?

**Comment by danifpdra** [comment]
Yes, the problem was that the data_collector_and_labeller.py reads a calibration_file that is given by the collect_data.launch, and because now we can configure the calibration with different configuration files with different names (and I was doing that), I noticed that the template for the collect_data.launch had a static argument:

`<arg name="config_file" default="$(find {{ c.package_name }})/calibration/config.yaml"/>`

So it was always reading the standard config.yaml file instead of the one I was using which has a different name. So I had to change the template and the configure_calibration_pkg so that the name given when configuring the package is passed to the launch file via template.

**Comment by miguelriemoliveira** [comment]
OK. great. Does it only occur for the data collector? No other module uses the config, right?

How about the set initial estimate?
