### ISSUE TITLE
Collection key error 000

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#515]
Hi @manuelgitgomes ,

I just recorded a dataset and was planning to use the dataset reviewer but It gives me this error:

> Traceback (most recent call last):
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/scripts/dataset_playback", line 234, in <module>
>     main()
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/scripts/dataset_playback", line 226, in main
>     visualizationFunction(models=models, selection=selection, clicked_points=clicked_points)
>   File "/home/mike/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/dataset_playback/visualization.py", line 609, in visualizationFunction
>     pointcloud_msg = graphics['ros']['sensors'][sensor_key]['collections'][selected_collection_key]['PointClouds']
> KeyError: '000'

I remember we changed the collections from 0,1,2 to 000, 001, 002 but then we rolled back theses changes ...
didn't we have an issue about this? I can't find it.

Can you help me ?

**Comment by miguelriemoliveira** [comment]
So I know why this is occurring. Its because we never used a dataset where a lidar sensor was not labelled. 

Will try to fix ...
