### ISSUE TITLE
Check camera info message exists in bag file.

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#576]
Because of #575 we noticed that if there is a rgb or depth sensor the camera_info msg is mandatory.

The configure should check that these messages do not exist in the bag and fail.

**Comment by miguelriemoliveira** [comment]
Implemented and tested in inesc drone calibration package.

Get and output as:

> Traceback (most recent call last):
>   File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/configure_calibration_pkg", line 15, in <module>
>     exec(compile(fh.read(), python_script, 'exec'), context)
>   File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/configure_calibration_pkg", line 282, in <module>
>     raise ValueError(Fore.RED + ' Topic ' + camera_info_topic + ' (from sensor ' + sensor_key +
> ValueError:  Topic /dji_osdk_ros/camera_info (from sensor fpv_camera) does not exist in the bag file. This topic must exist. Aborting configuration!
>
