### ISSUE TITLE
Improve configure_calibration_pkg output when xacro fails

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#579]
When the xacro command called directly from the configure_calibration_pkg fails, the output is not informative.
The atom configure prints this:

```
config_file = /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/calibration/config.yml
description file = /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro
Loading bagfile /home/mike/bagfiles/mmtbot/test_depth2.bag
Parsing description file /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro
Executing command: xacro /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro -o /tmp/description.urdf
Executing command: xacro /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro -o /tmp/description.urdf
Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/configure_calibration_pkg", line 148, in <module>
    description = URDF.from_xml_file(urdf_file)  # read the urdf file
  File "/usr/local/lib/python3.8/dist-packages/urdf_parser_py/xml_reflection/core.py", line 620, in from_xml_file
    xml_string = open(file_path, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/description.urdf'
```

and when running the xacro manually we get this:

```
xacro /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro -o /tmp/description.urdf
resource not found: velodyne_description
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/mike/workspaces/catkin_ws_rviz/src
ROS path [2]=/home/mike/workspaces/catkin_ws/src
ROS path [3]=/home/mike/workspaces/catkin_ws_rviz/src/rviz
ROS path [4]=/home/mike/workspaces/catkin_ws/src
ROS path [5]=/opt/ros/noetic/share
when processing file: /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro

```

The output of atom calibration should be more informative, something like "xacro failed, run command manually to see why", or a direct passthrough of the xacro command's output.

**Comment by miguelriemoliveira** [comment]
Output now is:

```
Executing command: xacro /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro -o /tmp/description.urdf
Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/configure_calibration_pkg", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/configure_calibration_pkg", line 150, in <module>
    raise ValueError(Fore.RED + 'Could not parse description file ' + Fore.BLUE + description_file + Style.RESET_ALL + '\nYou must manually run command:\n' + Fore.BLUE + xacro_cmd + Style.RESET_ALL + '\nand fix the problem before configuring your calibration package.')
ValueError: Could not parse description file /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro
You must manually run command:
xacro /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro -o /tmp/description.urdf
and fix the problem before configuring your calibration package.
```
