### ISSUE TITLE
Improve outputs in configure_calibration_pkg

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#587]
Not sure what is the best way, but should investigate and use a standard.

For example, latest error was:

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/configure_calibration_pkg", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/configure_calibration_pkg", line 106, in <module>
    config = atom_core.config_io.loadConfig(args['config_file'])
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_core/src/atom_core/config_io.py", line 145, in loadConfig
    fullpath, name, uri = uriReader(config['description_file'])
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_core/src/atom_core/config_io.py", line 77, in uriReader
    assert (rospack.get_path(uri.netloc)), 'Package ' + uri.netloc + ' does not exist.'
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: your_package
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/mike/workspaces/catkin_ws_rviz/src
ROS path [2]=/home/mike/workspaces/catkin_ws/src
ROS path [3]=/home/mike/workspaces/catkin_ws_rviz/src/rviz
ROS path [4]=/home/mike/workspaces/catkin_ws/src
ROS path [5]=/opt/ros/noetic/share
```

Which occurs because the urdf file is not found. Should give a better message.

**Comment by miguelriemoliveira** [comment]
Here are some guidelines:

https://stackoverflow.com/questions/2146618/raising-an-exception-vs-printing

**Comment by miguelriemoliveira** [comment]
Example of a create_calibration_pkg:

```
mike@focal src ➜ rosrun atom_calibration create_calibration_pkg --name test3
_______________________________________________________

           █████╗ ████████╗ ██████╗ ███╗   ███╗ 
          ██╔══██╗╚══██╔══╝██╔═══██╗████╗ ████║ 
          ███████║   ██║   ██║   ██║██╔████╔██║ 
          ██╔══██║   ██║   ██║   ██║██║╚██╔╝██║ 
   __     ██║  ██║   ██║   ╚██████╔╝██║ ╚═╝ ██║    _  
 / _|    ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝   | |    
 | |_ _ __ __ _ _ __ ___   _____      _____  _ __| | __ 
 |  _| '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ / 
 | | | | | (_| | | | | | |  __/\ V  V / (_) | |  |   <  
 |_| |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\ 
 https://github.com/lardemua/atom

Creating calibration package test3
_______________________________________________________

Creating package test3 on folder /home/mike/workspaces/catkin_ws/src
Executing command: cd /home/mike/workspaces/catkin_ws/src && catkin_create_pkg test3 rospy atom_calibration -a "Auto generated by Atomic Framework" -D "Calibration package created automatically by the atomic_calibration/create_calibration_pkg script. Check https://lardemua.github.io/atom_documentation/ for more information."
Executing command: mkdir /home/mike/workspaces/catkin_ws/src/test3/calibration
Executing command: mkdir /home/mike/workspaces/catkin_ws/src/test3/launch
Executing command: mkdir /home/mike/workspaces/catkin_ws/src/test3/rviz
Executing command: mkdir /home/mike/workspaces/catkin_ws/src/test3/urdf
Executing command: mkdir /home/mike/workspaces/catkin_ws/src/test3/urdf/optimized
Executing command: mkdir /home/mike/workspaces/catkin_ws/src/test3/scripts
Executing command: chmod +x /home/mike/workspaces/catkin_ws/src/test3/scripts/configure
Executing command: cp /home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/templates/config.yml /home/mike/workspaces/catkin_ws/src/test3/calibration/config.yml

Created calibration package test3 in /home/mike/workspaces/catkin_ws/src. Next steps:
   1. Edit the /home/mike/workspaces/catkin_ws/src/test3/calibration/config.yml to setup the calibration and; 
   2. Run: rosrun test3 configure

```

Example of a configure_calibration_pkg:

```
_______________________________________________________

           █████╗ ████████╗ ██████╗ ███╗   ███╗ 
          ██╔══██╗╚══██╔══╝██╔═══██╗████╗ ████║ 
          ███████║   ██║   ██║   ██║██╔████╔██║ 
          ██╔══██║   ██║   ██║   ██║██║╚██╔╝██║ 
   __     ██║  ██║   ██║   ╚██████╔╝██║ ╚═╝ ██║    _  
 / _|    ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝   | |    
 | |_ _ __ __ _ _ __ ___   _____      _____  _ __| | __ 
 |  _| '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ / 
 | | | | | (_| | | | | | |  __/\ V  V / (_) | |  |   <  
 |_| |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\ 
 https://github.com/lardemua/atom

Configuring calibration package mmtbot_calibration
_______________________________________________________

Loading config_file /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/calibration/config.yml
Loading bagfile /home/mike/bagfiles/mmtbot/test2.bag
Parsing description file /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro
Executing command: xacro /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_gazebo/urdf/mmtbot.urdf.xacro -o /tmp/description.urdf
Creating transformation tree using the urdf robot description ...
Running several verifications ... please wait ...
Checking if anchored sensor world_camera_rgb is valid ... [OK]
Checking for compressed image topics ... 
Topic /hand_camera/rgb/image_raw is in compressed format (/hand_camera/rgb/image_raw/compressed). Will setup a decompressor.
Topic /world_camera/rgb/image_raw is in compressed format (/world_camera/rgb/image_raw/compressed). Will setup a decompressor.
Checking for throttled topics ... 
Sensor hand_camera throttled to 5 Hz.
Sensor world_camera_rgb throttled to 5 Hz.
Checking for camera_info topic in bagfile ... [OK]
Checking if coordinate frames from config.yml exist in bagfile ... [OK]
Checking if transforms in config.yml are direct transformations ... [OK]
Checking consistency of configuration tf frames with the messages on corresponding topic ...[OK]
Checking if TF tree is connected ... [OK]
Transformations for sensors. Color coding is root link, to be calibrated, dynamic transformation, sensor data frame.
Path from world to sensor hand_camera:
[world, table, tabletop_table, base_link, base_link_inertia, shoulder_link, upper_arm_link, forearm_link, wrist_1_link, wrist_2_link, wrist_3_link, flange, hand_camera_link, hand_camera_rgb_frame, hand_camera_rgb_optical_frame]
Path from world to sensor world_camera_rgb:
[world, tripod, tripod_plate, tripod_right_support, world_camera_link, world_camera_rgb_frame, world_camera_rgb_optical_frame]
Setting up /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/launch/playbag.launch ...
Setting up /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/launch/set_initial_estimate.launch ...
Setting up /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/launch/collect_data.launch ...
Setting up /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/launch/calibrate.launch ...
Setting up /home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/launch/dataset_playback.launch ...
Setting up set_initial_estimate.rviz ...
	Generating rviz displays for sensor hand_camera with topic /hand_camera/rgb/image_raw (rgb)
	Generating rviz displays for sensor world_camera_rgb with topic /world_camera/rgb/image_raw (rgb)
Setting up collect_data.rviz ...
	Generating rviz displays for sensor hand_camera with topic /hand_camera/rgb/image_raw (rgb)
	Generating rviz displays for sensor world_camera_rgb with topic /world_camera/rgb/image_raw (rgb)
Setting up dataset_playback.rviz ...
	Generating rviz displays for sensor hand_camera with topic /hand_camera/rgb/image_raw (rgb)
	Generating rviz displays for sensor world_camera_rgb with topic /world_camera/rgb/image_raw (rgb)
Setting up calibrate.rviz ...
	Generating rviz displays for sensor hand_camera with topic /hand_camera/rgb/image_raw (rgb)
	Generating rviz displays for sensor world_camera_rgb with topic /world_camera/rgb/image_raw (rgb)

Created a calibration configuration summary. Use it to see if the calibration is well set up. Located at:
/home/mike/workspaces/catkin_ws/src/calibration/robots/mmtbot/mmtbot_calibration/calibration/summary.pdf

Successfully configured calibration package mmtbot_calibration in 1.58 seconds.
You can use the launch files:
roslaunch mmtbot_calibration playbag.launch
roslaunch mmtbot_calibration set_initial_estimate.launch
roslaunch mmtbot_calibration collect_data.launch
roslaunch mmtbot_calibration dataset_playback.launch
roslaunch mmtbot_calibration calibrate.launch
```
