### ISSUE TITLE
Error running dataset_playback 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#645]
When running the dataset playback I got the following error:

```
Traceback (most recent call last):
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/scripts/dataset_playback", line 233, in <module>
    main()
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/scripts/dataset_playback", line 225, in main
    visualizationFunction(models=models, selection=selection, clicked_points=clicked_points)
  File "/home/daniela/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/dataset_playback/visualization.py", line 609, in visualizationFunction
    graphics['ros']['sensors'][sensor_key]['PubDepthMarkers'].publish(markers)
KeyError: 'PubDepthMarkers'
```

@miguelriemoliveira , could you try to replicate?

Steps: 
1. create a the folder \larcc_subset inside the datasets folder. Unzip this dataset inside: https://uapt33090-my.sharepoint.com/:u:/g/personal/danielarato_ua_pt/EQtqsarpraxOgnh6hKdG0-wBeTdmRGGfV2FEW13WLrxLPw?e=8hqrsH

2. git pull larcc

3. run 

`roslaunch larcc_calibration dataset_playback.launch`

and run in another terminal

`clear && rosrun atom_calibration dataset_playback -json $ATOM_DATASETS/larcc_subset/train_real/dataset.json -ow`

**Comment by danifpdra** [comment]
I can run the dataset_playback for the camerabot without errors, which I find weird because it also has depth sensors

**Comment by danifpdra** [comment]
Found the error. Closing

**Comment by miguelriemoliveira** [comment]
Thanks @danifpdra ,

one less bug. Only about 5 million more to go.
