### ISSUE TITLE
Data collector crashes when parent folder does not exist

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#695]
When running

    roslaunch rgb_hand_eye_system_calibration collect_data.launch output_folder:=$ATOM_DATASETS/rgb_hand_eye_system/train overwrite:=true

there is an ugly crash like this: 

```terminal
Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/collect_data", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/collect_data", line 145, in <module>
    data_collector = DataCollectorAndLabeler(args, server, menu_handler)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py", line 59, in __init__
    os.mkdir(self.output_folder)  # Recreate the folder
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/datasets/rgb_hand_eye_system/train'
================================================================================REQUIRED process [collect_data-7] has died!
process has died [pid 86906, exit code 1, cmd /home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/collect_data -s 0.5 -o /home/mike/datasets/rgb_hand_eye_system/train -c /home/mike/workspaces/catkin_ws/src/calibration/atom/atom_examples/rgb_hand_eye_system/rgb_hand_eye_system_calibration/calibration/config.yml -ssl lambda sensor_name: False --overwrite __name:=collect_data __log:=/home/mike/.ros/log/70f418b0-86dd-11ee-831b-bf193a77fc3a/collect_data-7.log].
log file: /home/mike/.ros/log/70f418b0-86dd-11ee-831b-bf193a77fc3a/collect_data-7*.log
Initiating shutdown!
================================================================================
```

which occurs because the parent folder, i.e., $ATOM_DATASETS/rgb_hand_eye_system/  does not exist.

**Comment by miguelriemoliveira** [comment]
https://csatlas.com/python-create-directory/

**Comment by miguelriemoliveira** [comment]
Done. Creates parent directories if needed.
