### ISSUE TITLE
Rare timestamp error in collect data

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#743]
This occurs rarely but when it does I need to relaunch the data collector. I would say lets give it low priority foe now.

```terminal
average_time=3706213000001
[ERROR] [1701447959.472745, 3706.256958]: bad callback: <bound method InteractiveMarkerServer.processFeedback of <interactive_markers.interactive_marker_server.InteractiveMarkerServer object at 0x7f02a7606580>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/interactive_markers/interactive_marker_server.py", line 353, in processFeedback
    feedback_cb(feedback)
  File "/opt/ros/noetic/lib/python3/dist-packages/interactive_markers/menu_handler.py", line 143, in processFeedback
    context.feedback_cb(feedback)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/collect_data", line 32, in menuFeedback
    data_collector.saveCollection()
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py", line 412, in saveCollection
    transforms = self.getTransforms(self.abstract_transforms,
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py", line 347, in getTransforms
    transf = buffer.lookup_transform(ab['parent'], ab['child'], time)
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_ros/buffer.py", line 90, in lookup_transform
    return self.lookup_transform_core(target_frame, source_frame, time)
tf2.ExtrapolationException: Lookup would require extrapolation 0.001000001s into the future.  Requested time 3706.213000001 but the latest data is at time 3706.212000000, when looking up transform from frame [wrist_2_link] to frame [wrist_1_link]
```

**Comment by miguelriemoliveira** [comment]
Since the collector was entirely overhauled (#789), will close this one.
