### ISSUE TITLE
Error in filterCollectionsFromDataset

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#758]
When running 

    rosrun atom_calibration calibrate -json $ATOM_DATASETS/rgb_rgb_system_chessboard/train/dataset.json -v -rv -nig 0.1 0.1

```
Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/devel/lib/atom_calibration/calibrate", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 584, in <module>
    main()
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/calibrate", line 135, in main
    dataset = filterCollectionsFromDataset(dataset, args)  # filter collections
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_core/src/atom_core/dataset_io.py", line 576, in filterCollectionsFromDataset
    if not sensor_label['detected']:  # one pattern not detected is enough for this to be an incomplete collection
TypeError: 'bool' object is not subscriptable
INFO - 2023-12-03 03:35:53,509 - core - signal_shutdown [atexit]
```

**Comment by miguelriemoliveira** [comment]
Problem was the dataset was old. Updated and now its working.
