### ISSUE TITLE
Adapt inspect atom dataset to multipattern case

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#770]
rosrun atom_calibration inspect_atom_dataset -json dataset.json 

gives the error

```
Loaded dataset containing 2 sensors and 11 collections.
Dataset contains 2 sensors: ['lidar_right', 'rgb_left']
Traceback (most recent call last):
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/utilities/inspect_atom_dataset", line 207, in <module>
    main()
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/utilities/inspect_atom_dataset", line 69, in main
    if not collection['labels'][sensor_key]['detected']:
KeyError: 'lidar_right'
```

**Comment by miguelriemoliveira** [comment]
Fixed. Here's the output. I created a table per calibration pattern.

![image](https://github.com/lardemua/atom/assets/11350998/6dd31655-6575-4d86-bf77-3e9ed3aa1ca6)
