### ISSUE TITLE
Crash in data collection when cannot find pattern in collection

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#780]
```
[ERROR] [1702313992.845091, 2719.441515]: bad callback: <bound method InteractiveMarkerServer.processFeedback of <interactive_markers.interactive_marker_server.InteractiveMarkerServer object at 0x7f675fc4bf70>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/interactive_markers/interactive_marker_server.py", line 353, in processFeedback
    feedback_cb(feedback)
  File "/opt/ros/noetic/lib/python3/dist-packages/interactive_markers/menu_handler.py", line 143, in processFeedback
    context.feedback_cb(feedback)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/scripts/collect_data", line 32, in menuFeedback
    data_collector.saveCollection()
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/data_collector_and_labeler.py", line 534, in saveCollection
    estimatePatternPosesForCollection(dataset, collection_key)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/patterns.py", line 377, in estimatePatternPosesForCollection
    raise ValueError('Collection ' + collection_key + ' could not find pattern.')
ValueError: Collection 008 could not find pattern.
```

**Comment by miguelriemoliveira** [comment]
This should not crash. The collection could be saved anyway or not saved, but the script should not crash.

**Comment by miguelriemoliveira** [comment]
Duplicate of #765. The error message could be better. I will improve.
