### ISSUE TITLE
Rare error in rgb labeler

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#790]
[ERROR] [1702842698.262719, 9440.011314]: bad callback: <bound method RGBLabeler.labelData of <__main__.RGBLabeler object at 0x7f9cafbf9be0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/rgb_labeler", line 160, in labelData
    detector.drawKeypoints(image_gui, result, K=self.K, D=self.D, pattern_name=detector_key, color=color)
  File "/home/mike/workspaces/catkin_ws/src/calibration/atom/atom_calibration/src/atom_calibration/collect/patterns.py", line 188, in drawKeypoints
    cv2.drawFrameAxes(image, K, D, rvecs, tvecs, length)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/calib3d/src/calibration.cpp:556: error: (-5:Bad argument) One of required arguments is not a valid matrix in function 'cvProjectPoints2Internal'

**Comment by miguelriemoliveira** [comment]
Never had it again. Closing.
